ALTER TABLE iq_attempt_answers
  MODIFY COLUMN difficulty_level TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN weight DECIMAL(8,2) NULL DEFAULT NULL,
  MODIFY COLUMN correct_position TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN is_correct TINYINT(1) NULL DEFAULT NULL,
  MODIFY COLUMN points_earned DECIMAL(8,2) NULL DEFAULT NULL;
